export const AuditAction = {
  // AUTH
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  PASSWORD_RESET: 'PASSWORD_RESET',

  // ADMIN
  ADMIN_CREATE: 'ADMIN_CREATE',
  ADMIN_UPDATE: 'ADMIN_UPDATE',
  ADMIN_DELETE: 'ADMIN_DELETE',
  ROLE_CHANGE: 'ROLE_CHANGE',
  BAN_USER: 'BAN_USER',
  UNBAN_USER: 'UNBAN_USER',

  // TRANSACTIONS
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  BALANCE_CHANGE: 'BALANCE_CHANGE',

  // SECURITY
  FORBIDDEN_ACCESS: 'FORBIDDEN_ACCESS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  RATE_LIMIT: 'RATE_LIMIT',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditSeverity = {
  INFO: 'INFO',
  WARN: 'WARN',
  ERROR: 'ERROR',
  SECURITY: 'SECURITY',
  CRITICAL: 'CRITICAL',
} as const;

export type AuditSeverityType = (typeof AuditSeverity)[keyof typeof AuditSeverity];
